version: "2"
run:
  go: "1.26"
linters:
  default: none
  enable:
    - durationcheck
    - gocritic
    - gomodguard
    - govet
    - ineffassign
    - misspell
    - revive
    - staticcheck
    - unconvert
    - unused
    - usetesting
    - dupword
    - errorlint
    - intrange
    - nilnesserr
    - perfsprint
    - unparam
  settings:
    misspell:
      locale: US
    staticcheck:
      checks:
        - all
        - -ST1000
        - -SA1019
    revive:
      rules:
        - name: var-naming
          disabled: true
    gocritic:
      disabled-checks:
        - exitAfterDefer
formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
